site_name: Solid Developers Documentation
site_url: https://dev.solidproject.org/
site_description: How to build applications with Solid.
site_author: W3C Solid Community Group

repo_name: solid/dev
repo_url: https://github.com/solid/dev/
edit_uri: blob/main/docs/

copyright: Copyright &copy; - Present W3C Solid Community Group

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  highlightjs: true
  
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes

plugins:
  - search

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        # Need to fork the theme to make changes https://github.com/squidfunk/mkdocs-material/issues/3665#issuecomment-1060019924
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/solid/
    - icon: fontawesome/brands/gitter
      link: https://matrix.to/#/#solid_project:matrix.org
