site_name: Solid Developers Documentation
site_url: https://dev.solidproject.org/
site_description: How to build applications with Solid.
site_author: W3C Solid Community Group

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep purple
      accent: deep orange

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep purple
      accent: deep orange
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes

plugins:
  - search

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        # Need to fork the theme to make changes https://github.com/squidfunk/mkdocs-material/issues/3665#issuecomment-1060019924
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/solid/
    - icon: fontawesome/brands/gitter
      link: https://matrix.to/#/#solid_project:matrix.org

nav:
  - Welcome:
      - README.md
